apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: gitlab-runner4
    meta.helm.sh/release-namespace: gitlab
  creationTimestamp: "2023-03-26T05:49:13Z"
  generation: 1
  labels:
    app: gitlab-runner4
    app.kubernetes.io/managed-by: Helm
    chart: gitlab-runner-0.51.0
    heritage: Helm
    release: gitlab-runner4
  name: gitlab-runner4
  namespace: gitlab
  resourceVersion: "13557"
  uid: a9ec9314-c75a-4049-956d-53787e540eca
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitlab-runner4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configmap: 9d9fd00baf02b58b72e728b266c0a8521f6ebea124eee450997a28192ecbe707
        checksum/secrets: 2ddc8cdc043ed932a98c7b027d32374de2bcca48641c76dc6f7efa811f39006f
      creationTimestamp: null
      labels:
        app: gitlab-runner4
        chart: gitlab-runner-0.51.0
        heritage: Helm
        release: gitlab-runner4
    spec:
      hostAliases:
       - ip: "192.168.71.103"
         hostnames:
          - "web.nashannaguo.com"
          - "git.nashannaguo.com"
      containers:
      - command:
        - /usr/bin/dumb-init
        - --
        - /bin/bash
        - /configmaps/entrypoint
        env:
        - name: CI_SERVER_URL
          value: http://git.nashannaguo.com/
        - name: CLONE_URL
        - name: RUNNER_EXECUTOR
          value: kubernetes
        - name: REGISTER_LOCKED
          value: "true"
        - name: RUNNER_TAG_LIST
        image: gitlab/gitlab-runner:latest
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /entrypoint
              - unregister
              - --all-runners
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /configmaps/check-live
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: gitlab-runner4
        ports:
        - containerPort: 9252
          name: metrics
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - gitlab.*runner
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets
          name: projected-secrets
        - mountPath: /home/gitlab-runner/.gitlab-runner
          name: etc-gitlab-runner
        - mountPath: /configmaps
          name: configmaps
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65533
        runAsUser: 100
      terminationGracePeriodSeconds: 3600
      volumes:
      - emptyDir:
          medium: Memory
        name: runner-secrets
      - emptyDir:
          medium: Memory
        name: etc-gitlab-runner
      - name: projected-secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: runner-registration-token
                path: runner-registration-token
              - key: runner-token
                path: runner-token
              name: gitlab-runner4
      - configMap:
          defaultMode: 420
          name: gitlab-runner4
        name: configmaps
status:
  conditions:
  - lastTransitionTime: "2023-03-26T05:49:13Z"
    lastUpdateTime: "2023-03-26T05:49:13Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-03-26T05:49:13Z"
    lastUpdateTime: "2023-03-26T05:49:13Z"
    message: ReplicaSet "gitlab-runner4-69b5cf7d74" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
