apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        name: gitlab
    spec:
      hostAliases:
       - ip: "192.168.71.103"
         hostnames:
          - "web.nashannaguo.com"
          - "git.nashannaguo.com"
      containers:
      - name: gitlab
        image: sameersbn/gitlab:11.8.1
        imagePullPolicy: IfNotPresent
        env:
        - name: GITLAB_UNICORN_WORKERS
          value: "10"
        - name: GITLAB_SIDEKIQ_CONCURRENCY
          value: "50"
        - name: GITLAB_POSTGRESQL_SHARED_BUFFERS
          value: 4GB
        - name: TZ
          value: Asia/Shanghai
        - name: GITLAB_TIMEZONE
          value: Beijing
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_ROOT_PASSWORD
          value: nashannaguo123
        - name: GITLAB_ROOT_EMAIL
          value: nashannaguo@gmail.com
        - name: GITLAB_HOST
          value: git.nashannaguo.com
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "30022"
        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"
        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: password001
        - name: DB_NAME
          value: gitlab_production
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    name: gitlab
spec:
  ports:
    - name: http
      port: 6666
      targetPort: http
      # nodePort: 30081
    # - name: ssh
    #   port: 22
    #   targetport: ssh
      # nodePort: 30022
  # type: NodePort
  selector:
    name: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
  namespace: gitlab
  labels:
    name: gitlab-ssh
spec:
  ports:
    # - name: http
    #   port: 6666
    #   targetPort: http
      # nodePort: 30081
    - name: ssh
      port: 22
      targetPort: ssh
      nodePort: 30022
  type: NodePort
  selector:
    name: gitlab

---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: gitlab
#   namespace: kube-ops
#   # annotations:
#     # kubernetes.io/ingress.class: traefik # 注意这个，需要事先安装好traefik，若是使用的nginx-ingress，则需要删除这两行
# spec:
#   rules:
#   - host: git.nashannaguo.com
#     http:
#       paths: /
#       - backend:
#           serviceName: gitlab
#           servicePort: http
